### PR TITLE
Fix wrong mainClass in pom.xml

### PR DESCRIPTION
**Pull request by rpiw**
Replace wrong name of the mainClass to existing one. 
Solve issue #19, now  app runs with following command: 
`java -jar target/tetris-0.1.jar`

### CODE REVIEW

**Comment by rpiw** [comment]
I know Andry wanted to work on it, but it was annoying to test solution to my issue when I was unable to run the app with the way I want. If I build with maven, I want to run a jar.

**Comment by AndriiVel** [comment]
And where are the tests? :)

**Comment by rpiw** [comment]
How do I test pom.xml?

**Comment by AndriiVel** [comment]
Exactly :-D

**Comment by AndriiVel** [comment]
Not pom.xml, but the fact that the issue is fixed.

**Comment by rpiw** [comment]
Well, this is task for you!

**Comment by rpiw** [comment]
I close it, Andry made a better job

**Comment by AndriiVel** [comment]
I'll appreciate your feedback on it :-)

**Pull request closed without merging**
