### PR TITLE
16 elapsed time

### PR DESCRIPTION
**Pull request by fabianazabala**
#16 Elapsed time is presented issue. My solution was to create a new class that calculates the time passed between the beginning and the end of the game and prints such time onto the screen in the hh:mm:ss format ar required.
@pkierat-epam

### CODE REVIEW

**Comment by pkierat-epam** [comment]
According to the requirements, the clock should be updated in every cycle of the game, not just printed at the end.

**Comment by TJB4epam** [comment]
I've just merged other changes. Make sure you have all you need and that this works after you merge the new master. GitHub for one reports that this PR has conflicts in the Tetris file.

**Review by TJB4epam — CHANGES_REQUESTED** [review]
Merely marking here that without conflict resolution this will not be reviewed.

**Comment by TJB4epam** [comment]
I assume you don't have time ATM, therefore I am closing the pull request. Once you have it fixed, do reopen. Thank you.

**Pull request closed without merging**
