### PR TITLE
101 Block and Printer fields changed to private

### PR DESCRIPTION
**Pull request by Slawek-Sandbox**
Changed:
- Block's fields image, rows and cols
- Printer's field out
to private

### CODE REVIEW

**Review by TJB4epam — CHANGES_REQUESTED** [review]
Nice idea. Please also bump the POM version to join the conflicts rat race. :-)

**Comment by Slawek-Sandbox** [comment]
POM version is 0.6 for this PR (+0.1 comparing to master). Should I increase it?

**Comment by Slawek-Sandbox** [comment]
POM version bumped to 0.6

**Comment by TJB4epam** [comment]
This Wednesday we will focus on aggresively closing PRs. Just FYI.

**Comment by Slawek-Sandbox** [comment]
POM version bumped once again. No merge conflict (at least as for now :) ).

**Comment by Slawek-Sandbox** [comment]
Sure, np. The POM's removed from PR.

**Review by TJB4epam — APPROVED** [review]
yep! thank you!

**Pull request merged**
